# logging.ini
[loggers]
keys=root,bot,web

[handlers]
keys=consoleHandler,fileHandler

[formatters]
keys=consoleFormatter,fileFormatter

############################
# Loggers
############################
[logger_root]
level=DEBUG
handlers=consoleHandler,fileHandler

[logger_bot]
level=DEBUG
handlers=consoleHandler,fileHandler
qualname=bot
propagate=0

[logger_web]
level=DEBUG
handlers=consoleHandler,fileHandler
qualname=web
propagate=0

############################
# Handlers
############################
# Console Handler with colorized output
[handler_consoleHandler]
class=StreamHandler
level=DEBUG
formatter=consoleFormatter
args=(sys.stdout,)

# Rotating File Handler for persistent logs
[handler_fileHandler]
class=handlers.RotatingFileHandler
level=ERROR
formatter=fileFormatter
args=('TELEGRAM_BOT.log', 'a', 5*1024*1024, 5)  # 5 MB per file, 5 backups

############################
# Formatters
############################
[formatter_consoleFormatter]
format=%(asctime)s - %(levelname)s - %(name)s - %(message)s
datefmt=%H:%M:%S

[formatter_fileFormatter]
format=[%(asctime)s:%(name)s:%(lineno)d:%(levelname)s] %(message)s
datefmt=%Y-%m-%d %H:%M:%S
